In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('homeprices.csv')
df.head(10)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000
5     west windsor  2600  585000
6     west windsor  2800  615000
7     west windsor  3300  650000
8     west windsor  3600  710000
9      robinsville  2600  575000

In [4]:
dummies=pd.get_dummies(df['town'])
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [5]:
merged=pd.concat([df,dummies],axis=1)
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [10]:
final_df=merged.drop(['town','west windsor'],axis=1)

In [12]:
final_df

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [14]:
x=final_df.drop('price',axis=1)
x.head()

area  monroe township  robinsville
0  2600                1            0
1  3000                1            0
2  3200                1            0
3  3600                1            0
4  4000                1            0

In [16]:
y=final_df['price']
y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [17]:
model.fit(x,y)

LinearRegression()

In [21]:
model.intercept_

249790.36766292533

In [19]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [22]:
model.predict(x)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [24]:
model.score(x,y)*100

95.73929037221873

In [25]:
model.predict([[3400,0,0]])

array([681241.66845839])

### LabelEncoder

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [27]:
data=df
data.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [28]:
data['town']=le.fit_transform(data['town'])
data

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [30]:
x_new=data.drop('price',axis=1)
x_new.head()

town  area
0     0  2600
1     0  3000
2     0  3200
3     0  3600
4     0  4000

In [31]:
y_new=data['price']
y_new.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [32]:
model.fit(x_new,y_new)

LinearRegression()

In [33]:
model.score(x_new,y_new)

0.9552018104317441

In [41]:
model.predict([['2','3400']])

C:\Users\visha\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


array([682889.14751237])